### ISSUE TITLE
[BUG] Test error on v0.1-alpha err num: -1073741676

### ISSUE THREAD

**Issue by ctr-branch** [nonunknown/ctr-modding-kit#1]
**CTRMK version:**
v0.1-alpha

**OS/device including version:**
Windows 10, Ryzen 2600X, 16gb, RTX2080

**Issue description:**
Using epsxe, US version of cue. and 5501 bios.
[Image](https://imgur.com/a/Vmk6vIv)

**Steps to reproduce:**
Use epsxe, US version of the game. and 5501 bios.

**Comment by ctr-branch** [comment]
epsxe is in C-drive, cue and bios is in D-drive

**Comment by ctr-branch** [comment]
[image](https://imgur.com/a/F9BDQNl)
all files in the same drive, removing spaces. still the same error.

**Comment by ctr-branch** [comment]
did remove save.tres every time

**Comment by ctr-branch** [comment]
was using admin rights everytime launching the program.

**Comment by nonunknown** [comment]
**Possible Solutions**

* Make sure when you run you `ctr.cue` direcly from epsxe.exe the game runs. After that, open CTRMK again and set paths & click test
* If yous bios isnt SCPH1001 try it!
